"""FFmpeg media adapter for export, inspection and assembly.

ETAPA 13 adds the two primitives a multi-scene cut needs and that were missing:

  * `probe` returned `{"raw": stdout}` — ffprobe's JSON was handed back unparsed
    and nothing in the repository called it, so no code could read a clip's
    duration, frame rate or size. It is now parsed, and `raw` is kept so the
    shape only grows.
  * there was no way to put two clips together. `export_h264` takes a single
    source, so a five-scene storyboard produced five orphan files. `concat` is
    the assembly step.

Argument building lives in module-level pure functions (`probe_fields`,
`concat_command`) so it is testable without FFmpeg installed. This sandbox has no
`ffmpeg` on PATH, and a command that cannot be executed here should still be a
command whose shape is verified.
"""
import json
import shutil
import subprocess
import tempfile
from pathlib import Path


QUALITY = {
    "720p": (1280, 720, "4M"),
    "1080p": (1920, 1080, "8M"),
    "2k": (2560, 1440, "16M"),
    "4k": (3840, 2160, "35M"),
}

#: Container/audio settings shared by export and assembly, so a single clip and
#: a finished cut are encoded the same way and can be concatenated afterwards.
VIDEO_CODEC_ARGS = ("-c:v", "libx264", "-pix_fmt", "yuv420p")
AUDIO_CODEC_ARGS = ("-c:a", "aac", "-b:a", "192k")


class MediaError(RuntimeError):
    pass


def probe_fields(payload: str) -> dict[str, object]:
    """Turn ffprobe's JSON into the few facts a timeline needs.

    Tolerant on purpose: a malformed or partial payload yields what could be
    read rather than raising, because a caller asking for duration should get
    `None` and decide, not catch a parser error.
    """

    try:
        data = json.loads(payload)
    except (ValueError, TypeError):
        return {}
    if not isinstance(data, dict):
        return {}

    fields: dict[str, object] = {}
    fmt = data.get("format") or {}
    if isinstance(fmt, dict):
        duration = fmt.get("duration")
        if duration is not None:
            try:
                fields["duration_seconds"] = round(float(duration), 3)
            except (TypeError, ValueError):
                pass
        if fmt.get("format_name"):
            fields["container"] = str(fmt["format_name"])

    streams = data.get("streams") or []
    if isinstance(streams, list):
        for stream in streams:
            if not isinstance(stream, dict):
                continue
            kind = stream.get("codec_type")
            if kind == "video" and "width" not in fields:
                fields["width"] = stream.get("width")
                fields["height"] = stream.get("height")
                if stream.get("avg_frame_rate"):
                    fields["fps"] = _parse_rate(str(stream["avg_frame_rate"]))
                if stream.get("codec_name"):
                    fields["video_codec"] = str(stream["codec_name"])
            elif kind == "audio" and "audio_codec" not in fields:
                if stream.get("codec_name"):
                    fields["audio_codec"] = str(stream["codec_name"])
    return fields


def _parse_rate(rate: str) -> float | None:
    """ffprobe reports frame rate as `24000/1001`."""

    try:
        if "/" in rate:
            numerator, denominator = rate.split("/", 1)
            denominator_value = float(denominator)
            return round(float(numerator) / denominator_value, 3) if denominator_value else None
        return round(float(rate), 3)
    except (TypeError, ValueError, ZeroDivisionError):
        return None


def scale_filter(width: int, height: int) -> str:
    """Letterbox to the target box without stretching the image."""

    return (
        f"scale={width}:{height}:force_original_aspect_ratio=decrease,"
        f"pad={width}:{height}:(ow-iw)/2:(oh-ih)/2"
    )


def concat_command(
    sources: list[str],
    destination: str,
    *,
    list_file: str,
    quality: str = "1080p",
    fps: int = 24,
    audio: str | None = None,
) -> list[str]:
    """Build the argv that assembles clips into one file.

    Re-encodes rather than stream-copying: clips generated by different providers
    do not share a timebase or a pixel format, and `-c copy` across them produces
    a file that plays wrong in exactly the way that is expensive to debug later.
    """

    if quality not in QUALITY:
        raise MediaError(f"Unsupported quality: {quality}")
    if not sources:
        raise MediaError("Nothing to assemble: the timeline has no rendered clips")

    width, height, bitrate = QUALITY[quality]
    command = [
        "ffmpeg", "-y",
        "-f", "concat", "-safe", "0", "-i", list_file,
        "-vf", scale_filter(width, height),
        "-r", str(fps),
        *VIDEO_CODEC_ARGS,
        "-b:v", bitrate,
    ]
    if audio:
        # The bed is a second input, mapped explicitly, and `-shortest` stops a
        # long track from holding the file open past the last frame.
        command += ["-i", audio, "-map", "0:v:0", "-map", "1:a:0", *AUDIO_CODEC_ARGS, "-shortest"]
    else:
        command.append("-an")
    command += ["-movflags", "+faststart", destination]
    return command


class FFmpegService:
    @property
    def available(self) -> bool:
        return shutil.which("ffmpeg") is not None

    def capabilities(self) -> dict[str, object]:
        return {"available": self.available, "binary": shutil.which("ffmpeg"), "formats": ["mp4", "gif", "webm", "mov"]}

    def probe(self, source: str) -> dict[str, object]:
        """Inspect a media file and return its parsed facts.

        Keeps `raw` so callers that wanted the untouched payload still get it.
        """

        if not self.available:
            raise MediaError("FFmpeg is not installed")
        result = subprocess.run(["ffprobe", "-v", "quiet", "-print_format", "json", "-show_format", "-show_streams", source], capture_output=True, text=True, timeout=15)
        if result.returncode != 0:
            raise MediaError(result.stderr.strip() or "Could not inspect media")
        return {"raw": result.stdout, **probe_fields(result.stdout)}

    def export_h264(self, source: str, destination: str, quality: str = "1080p", fps: int = 24) -> str:
        if not self.available:
            raise MediaError("FFmpeg is not installed")
        if quality not in QUALITY:
            raise MediaError(f"Unsupported quality: {quality}")
        width, height, bitrate = QUALITY[quality]
        Path(destination).parent.mkdir(parents=True, exist_ok=True)
        command = ["ffmpeg", "-y", "-i", source, "-vf", scale_filter(width, height), "-r", str(fps), *VIDEO_CODEC_ARGS, "-b:v", bitrate, "-movflags", "+faststart", destination]
        result = subprocess.run(command, capture_output=True, text=True, timeout=900)
        if result.returncode != 0:
            raise MediaError(result.stderr[-1000:] or "FFmpeg export failed")
        return destination

    def concat(
        self,
        sources: list[str],
        destination: str,
        *,
        quality: str = "1080p",
        fps: int = 24,
        audio: str | None = None,
    ) -> str:
        """Assemble rendered clips into one file, in the given order.

        Order is the caller's: this adapter does not re-sort a cut. A timeline
        decides the sequence, `concat` executes it.
        """

        if not self.available:
            raise MediaError("FFmpeg is not installed")
        Path(destination).parent.mkdir(parents=True, exist_ok=True)
        with tempfile.NamedTemporaryFile("w", suffix=".txt", delete=False) as handle:
            for source in sources:
                # The concat demuxer reads this file as a script; a quote or a
                # backslash in a path would change what it executes.
                escaped = str(source).replace("\\", "\\\\").replace("'", r"\'")
                handle.write(f"file '{escaped}'\n")
            list_file = handle.name
        command = concat_command(
            sources, destination, list_file=list_file, quality=quality, fps=fps, audio=audio
        )
        try:
            result = subprocess.run(command, capture_output=True, text=True, timeout=1800)
        finally:
            Path(list_file).unlink(missing_ok=True)
        if result.returncode != 0:
            raise MediaError(result.stderr[-1000:] or "FFmpeg assembly failed")
        return destination


media = FFmpegService()
